# Generated by Django 5.0.3 on 2025-11-02 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SysPermission',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='权限名称')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='权限标识')),
                ('request_method', models.CharField(choices=[('GET', 'GET'), ('POST', 'POST'), ('PUT', 'PUT'), ('DELETE', 'DELETE')], max_length=10, verbose_name='请求方式')),
                ('url_path', models.CharField(max_length=200, verbose_name='接口地址')),
                ('remark', models.CharField(blank=True, max_length=200, null=True, verbose_name='备注')),
            ],
            options={
                'db_table': 'sys_permission',
            },
        ),
        migrations.CreateModel(
            name='SysRolePermission',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'sys_role_permission',
            },
        ),
    ]
