# Generated by Django 5.0.3 on 2025-11-02 09:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('permission', '0001_initial'),
        ('sysmenu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='syspermission',
            name='menu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='sysmenu.sysmenu'),
        ),
        migrations.AddField(
            model_name='sysrolepermission',
            name='permission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='permission.syspermission'),
        ),
    ]
