# Generated by Django 5.0.3 on 2025-11-02 09:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('permission', '0002_initial'),
        ('sysrole', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sysrolepermission',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sysrole.sysrole'),
        ),
    ]
