# Generated by Django 5.0.3 on 2025-11-02 09:53

import auth.sysuser.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('client_ip', models.GenericIPAddressField()),
                ('user_info', models.CharField(max_length=100)),
                ('method', models.CharField(max_length=10)),
                ('path', models.CharField(max_length=200)),
                ('status_code', models.IntegerField()),
                ('duration', models.DecimalField(decimal_places=2, max_digits=10)),
                ('os_info', models.CharField(max_length=100)),
                ('browser_info', models.CharField(max_length=100)),
                ('permission_info', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='opsUser',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100, unique=True)),
                ('realname', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telephone', models.CharField(blank=True, max_length=11)),
                ('is_active', models.BooleanField(default=True)),
                ('status', models.IntegerField(choices=[(1, 'Active'), (2, 'Unactive'), (3, 'Locked')], default=2)),
                ('avatar', models.CharField(default='111.jpg', max_length=255, null=True, verbose_name='用户头像')),
                ('create_time', models.DateField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('latest_token', models.CharField(blank=True, max_length=255, null=True, verbose_name='最新Token')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'ordering': ('-last_login',),
            },
            managers=[
                ('objects', auth.sysuser.models.opsUserManager()),
            ],
        ),
    ]
