# Generated by Django 5.0.3 on 2025-11-02 09:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SysMenu',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, null=True, unique=True, verbose_name='菜单名称')),
                ('text', models.CharField(max_length=50, unique=True, verbose_name='菜单标签')),
                ('icon', models.CharField(max_length=100, null=True, verbose_name='菜单图标')),
                ('parent_id', models.IntegerField(verbose_name='父菜单ID')),
                ('order_num', models.IntegerField(verbose_name='显示顺序')),
                ('path', models.CharField(max_length=200, verbose_name='路由地址')),
                ('component', models.CharField(blank=True, max_length=255, null=True, verbose_name='组件路径')),
                ('menu_type', models.CharField(max_length=1, verbose_name='菜单类型（M目录 C菜单 F按钮）')),
                ('perms', models.CharField(blank=True, max_length=100, null=True, verbose_name='权限标识')),
                ('create_time', models.DateField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('remark', models.CharField(blank=True, max_length=500, null=True, verbose_name='备注')),
            ],
            options={
                'db_table': 'sys_menu',
            },
        ),
        migrations.CreateModel(
            name='SysRoleMenu',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'sys_role_menu',
            },
        ),
        migrations.AddConstraint(
            model_name='sysmenu',
            constraint=models.UniqueConstraint(fields=('parent_id', 'order_num'), name='uniq_parent_order'),
        ),
        migrations.AddField(
            model_name='sysrolemenu',
            name='menu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sysmenu.sysmenu'),
        ),
    ]
