# Generated by Django 5.0.3 on 2025-11-02 09:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SysRole',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='角色名称')),
                ('code', models.CharField(max_length=100, unique=True, verbose_name='角色权限字符串')),
                ('create_time', models.DateField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('remark', models.CharField(max_length=500, null=True, verbose_name='备注')),
            ],
            options={
                'db_table': 'sys_role',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='SysUserRole',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sysrole.sysrole')),
            ],
            options={
                'db_table': 'sys_user_role',
            },
        ),
    ]
